###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cp4a-pfs-operator-controller-manager
  labels:
    app.kubernetes.io/instance: ibm-cp4a-pfs-operator
    app.kubernetes.io/managed-by: ibm-cp4a-pfs-operator
    app.kubernetes.io/name: ibm-cp4a-pfs-operator
    release: 24.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-cp4a-pfs-operator  
  template:
    metadata:
      labels:
        name: ibm-cp4a-pfs-operator
        app.kubernetes.io/instance: ibm-cp4a-pfs-operator
        app.kubernetes.io/managed-by: ibm-cp4a-pfs-operator
        app.kubernetes.io/name: ibm-cp4a-pfs-operator
        release: 24.0.0
      annotations:
        cloudpakId: "94a9c8c358bb43ba8fbdea62e7e166a5"
        cloudpakName: "IBM Cloud Pak for Business Automation"
        cloudpakVersion: "24.0.0"
        productChargedContainers: ""
        productCloudpakRatio: '1:1'
        productID: 94a9c8c358bb43ba8fbdea62e7e166a5
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productName: "Process Federation Server - CP4BA"
        productVersion: "24.0.0"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ibm-cp4a-pfs-operator-controller-manager
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - s390x
                - ppc64le
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - s390x
                - ppc64le
      containers:
        - name: operator
          # Replace this with the built image name
          image: icr.io/cpopen/icp4a-pfs-operator:24.0.0
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 20Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
      - name: "ibm-entitlement-key"
      terminationGracePeriodSeconds: 10
