###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-workflow-operator
  labels:
    app.kubernetes.io/instance: ibm-dba-workflow
    app.kubernetes.io/managed-by: ibm-dba-workflow
    app.kubernetes.io/name: ibm-dba-workflow
    release: 24.0.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-workflow-operator
subjects:
- kind: ServiceAccount
  name: ibm-workflow-operator-sa
  namespace: <NAMESPACE>
