###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-workflow-operator-sa
  labels:
    app.kubernetes.io/name: ibm-dba-workflow
    app.kubernetes.io/instance: ibm-dba-workflow
    app.kubernetes.io/managed-by: ibm-dba-workflow
    release: 24.0.0
automountServiceAccountToken: true
